Repository AISC-25SS/git-practice-study, pull requests merged in 2025-05, with the labels that each got.

#8 feat: #2 Hello World 출력 기능 구현
  src/seungjun/Hello.java
Labels: ✨ feat, 👤 승준

#13 feat : #6 Hello World 출력 기능 구현
  src/Eunhye/Hello.java
Labels: ✨ feat, 👤 은헤

#11 feat : #7 Hello World 출력 기능 구현
  src/Main.java
  src/jongbin/Hello.java
Labels: ✨ feat, 👤 종빈

#9 Feat/#5 hello jihoon
  README.md
  src/jihoon/Hello.java
  src/jihoon/JihoonPractice.java
  src/jihoon/Order/Order.java
  src/jihoon/Order/OrderRepository.java
Labels: 👤 지훈
